LLVM 18 support
pocl/pocl pull request #1424
Opened 2024-02-20 14:09 UTC by franz

2024-02-20 14:35 UTC, franz commented
A few tests still fail:

```
The following tests FAILED:
	106 - regression/barrier_between_two_for_loops_cbs (Failed)
	142 - regression/test_alignment_with_dynamic_wg_114_cbs (Failed)
	144 - regression/test_alignment_with_dynamic_wg_117_cbs (Failed)
	146 - regression/test_alignment_with_dynamic_wg_225_cbs (Failed)
	148 - regression/test_alignment_with_dynamic_wg_173_cbs (Failed)
	150 - regression/test_alignment_with_dynamic_wg_183_cbs (Failed)
	152 - regression/test_alignment_with_dynamic_wg_283_cbs (Failed)
	154 - regression/test_alignment_with_dynamic_wg_332_cbs (Failed)
	156 - regression/test_alignment_with_dynamic_wg_323_cbs (Failed)
```

...all of them are related to CBS. @fodinabor  any ideas ? do you have time to take a look ?

2024-02-20 16:21 UTC, pjaaskel requested changes
Tiny nit. Can you add a LLVM 18 CI with this PR?

2024-02-20 16:21 UTC, pjaaskel commented on cmake/LLVM.cmake
> +       #if (LLVM_MAJOR < 18)
Shouldn't cpp macros start from column 0?

2024-02-22 12:11 UTC, pjaaskel commented
Sorry we are a bit busy too, but we can disable CBS (or XFAIL the tests) for LLVM 18 until it's fixed to get the LLVM 18 support in.

2024-02-27 12:09 UTC, franz commented on cmake/LLVM.cmake
> +       #if (LLVM_MAJOR < 18)
fixed

2024-02-27 12:21 UTC, pjaaskel commented on CMakeLists.txt
> +set(DEFAULT_KERNEL_CL_FLAGS  "-xcl -fno-stack-protector -fPIC -fno-jump-tables ${FLOATCONV_FLAG} ${OPAQUE_PTR_FLAGS}")
Can you add a comment why we add no-jump-tables? It's easy to forget.

2024-02-27 12:21 UTC, pjaaskel commented on cmake/LinkTestClang.cc
> +#include <clang/Basic/Diagnostic.h>
Can you add the (c)/license text?

2024-02-27 12:21 UTC, pjaaskel commented on cmake/LinkTestLLVM.cc
> +#include "llvm/IR/LLVMContext.h"
Same here. License text is missing.

2024-02-27 12:22 UTC, pjaaskel commented on cmake/LinkTestLLVM.cc
> +#include "llvm/IR/Module.h"
Please use #include <> as we are not in LLVM source tree.

2024-02-27 12:22 UTC, pjaaskel commented on lib/CL/pocl_llvm_build.cc
> +  ss << "-fno-jump-tables ";
Also pls add the comment here so we won't forget (I already did).

2024-02-27 12:27 UTC, pjaaskel commented on lib/llvmopencl/DebugHelpers.cc
> +#include "llvm/Analysis/RegionInfo.h"
Pls use <>

2024-02-27 12:28 UTC, pjaaskel commented on lib/llvmopencl/DebugHelpers.cc
> +  if (Regions!=nullptr && Regions->size()) {
White space issue, can you run the formatter?

2024-02-27 12:29 UTC, pjaaskel commented on lib/llvmopencl/LLVMUtils.h
> +// fixes switch statements that have a default case that is a simple unreachable
```suggestion
// Fixes switch statements that have a default case that is a simple unreachable
```

2024-02-27 12:29 UTC, pjaaskel commented on lib/llvmopencl/LLVMUtils.h
> +// inside conditional blocks.
```suggestion
// inside conditional blocks although they are not.
```

2024-02-27 12:29 UTC, pjaaskel commented on lib/llvmopencl/LLVMUtils.h
> +// unreachable blocks. However i couldn't find any working way to make PDT
```suggestion
// unreachable blocks. However I couldn't find any working way to make PDT
```

2024-02-27 12:30 UTC, pjaaskel commented on lib/llvmopencl/LLVMUtils.h
> +// ignore blocks with unreachable inst.
```suggestion
// ignore blocks with an unreachable inst.
```

2024-02-27 12:31 UTC, pjaaskel commented on lib/llvmopencl/OptimizeWorkItemGVars.cc
> +// TODO: we should replace the magic global variables with function calls
```suggestion
// TODO: we should replace the magic global variables marking the work-item IDs with function calls or intrinsics.
```

2024-02-27 12:32 UTC, pjaaskel commented on lib/llvmopencl/OptimizeWorkItemGVars.cc
> +/*
Please remove commented out code.

2024-02-27 12:32 UTC, pjaaskel commented on lib/llvmopencl/OptimizeWorkItemGVars.cc
> +//        U->getType()->dump();
Please remove commented out code.

2024-02-27 12:33 UTC, pjaaskel commented on lib/llvmopencl/WorkitemReplication.cc
> +  //pocl::dumpCFG(F, F.getName().str() + ".before_repl.dot",
Pls move these to the #if 0 block below?

2024-02-28 11:56 UTC, franz commented
```
[2024-02-27 14:50:58.734061576] POCL: in fn read at line 193:
  *** ERROR ***  |     ERROR |  Read error on reentrant_read(fd, req, request->req_size, &request->req_read), fd=9, reason: Bad address
[2024-02-27 14:50:58.734090907] POCL: in fn connectPeer at line 150:
  *** ERROR ***  |     ERROR |  PH: error on read_full(PeerFd, &Reply, sizeof(Reply), netstat): Connection reset by peer
```

@jansol  is the RDMA CI working nowadays ?

2024-02-28 14:00 UTC, jansol commented
#1433 should fix the RDMA CI

2024-03-05 16:05 UTC, merged

2024-03-11 17:45 UTC, franz commented
Hi @fodinabor, do you have time to look into the CBS failure a bit more ? Unfortunately removing the instcombine between `loop-barriers` and `barrier-tail` passes still makes `loopvec` fail (because the `phi`s are not handled), but it's unclear to me what causes `instcombine` with CBS to replace the `for.body` with poison.