add new cl_pocl_command_buffer extension APIs
pocl/pocl pull request #1432
Opened 2024-02-22 22:14 UTC by franz

2024-02-23 08:10 UTC, pjaaskel requested changes
Thanks for dusting this off. Can you add a mention of these to the release notes?
Also, the *Rect functions do not seem to use the SVM cl_mem shadow buffer refactoring. I wonder do the implicit migrations work with PoCL-R?

2024-02-23 08:10 UTC, pjaaskel commented on lib/CL/clCommandReadBufferPOCL.c
> +   Copyright (c) 2022-2023 Michal Babej / Intel Finland Oy
Also some other headers have an old year range.

2024-02-23 10:04 UTC, franz commented
> Also, the *Rect functions do not seem to use the SVM cl_mem shadow buffer refactoring. 

Yes, this is a rebased & slightly cleaned up code from ~1 year ago, before the SVM cl_mem was merged.

> I wonder do the implicit migrations work with PoCL-R?

The ones you have changed should still work, these new ones do not, since they use the SVM pointer directly. But it should work with CPU devices. Also missing are tests; i did limited testing with chipStar graph PR when the code was written, but we should  have more tests (possibly in OpenCL-CTS).

2024-02-28 14:00 UTC, jansol commented
#1433 should fix the RDMA CI

2024-03-04 15:31 UTC, merged