Defined built-in kernels (DBK) extension with infrastructure for more drivers
pocl/pocl pull request #1521
Opened 2024-07-25 10:36 UTC by franz

This fixes a bunch of problems in the original PR (#1503).

- adds proper CMake support for libxsmm
- builtin_kernels.cc: converted from C++ to C
- simplified the `cl_tensor_desc` struct
- removed `custom_kernel_runner`, use existing paths for execution
- implemented a more structured API closer (but not identical) to the draft document on the extension
- extended CPU support of GEMM DBK to types other than FP32

2024-07-30 15:00 UTC, pjaaskel requested changes
This is now looking quite good. Only small ones. @TopiLeppanen please take a look at this PR from the perspective of FPGA/AlmaIF implementation before we pull this in and test that it doesn't break your work? @linehill can you update the extension specs to match this prototype and point from the extension PR to this PR?

2024-08-01 09:02 UTC, linehill commented on include/CL/cl_exp_tensor.h
> +} cl_tensor_datatype_union;
What if we need to pass objects larger than `sizeof(cl_double)` in the future? We can’t update this union due to potential ABI breakage.

2024-08-02 10:35 UTC, franz commented on lib/CL/clCreateProgramWithDefinedBuiltInKernels.c
> +  const char **kernel_names,
added a check for uniqueness

2024-08-02 11:13 UTC, franz commented on include/CL/cl_exp_defined_builtin_kernels.h
> +typedef cl_kernel (CL_API_CALL *clCreateBuiltinKernelWithAttributesEXP_fn) (
"clCreateProgramWithDefinedBuiltInKernels" is the only new API function in this PR

2024-08-06 08:24 UTC, TopiLeppanen commented
Hello, I fixed some breakage in the AlmaIF driver related to the builtin_kernels.hh being converted to C.
Hope you don't mind I pushed it already here, since that seemed most convenient.

There was a missing pocl_BIDescriptor for the first built-in kernel in the list: pocl.copy.i8 which I added.

2024-08-13 08:13 UTC, merged