remote: Abstract sockets away from business logic
pocl/pocl pull request #1610
Opened 2024-10-10 16:33 UTC by jansol

This should help make the remote a bit more flexible at runtime by abstracting away some of the socket- and TCP-specific parts and tacking on some metadata to the connection handle. The end goal is to eventually also support transports that don't map directly to the socket API. Maybe even merge the socket and RDMA code paths at some point.

As part of that I've changed vsock support from a default-off option to always be enabled if the requisite header is present. Eventually it would be nice to revive the UNIX domain socket support using this setup as well.

@xvim If you are still maintaining vsock support, could you check that this didn't break anything related to that? There should not be any changes, but I don't have any setup at hand where I could confirm that.

2024-10-11 09:32 UTC, xvim commented
I did a quick test. vsock is now enabled by default when the system headers are present, as intended.
However, I've encountered an issue with the remote functionality, even when using a tcp connection. When I ran clinfo to initiate a connection the second time, the connection failed. Here's the log of the problem:
```
liucong@liucong:~/pocl/build$ export POCL_REMOTE0_PARAMETERS='192.168.122.1:9999/0'
liucong@liucong:~/pocl/build$ 
liucong@liucong:~/pocl/build$ clinfo -l
[2024-10-11 09:05:18.599813993] PoCL: in fn find_or_create_server at line 1535:
 |    REMOTE |  using host 192.168.122.1 with port 9999
[2024-10-11 09:05:18.601045658] PoCL: in fn find_or_create_server at line 1570:
 |    REMOTE |  Received session id 1, key 36c5899806ed56a664c16596ea367243
[2024-10-11 09:05:18.601963160] PoCL: in fn find_or_create_server at line 1733:
 |    REMOTE |  Connected to 192.168.122.1:9999 which has 1 devices
[2024-10-11 09:05:18.602232745] PoCL: in fn pocl_network_init_device at line 1865:
 |    REMOTE |  Setting up remote device with PLATFORM 0 / DEVICE 0
[2024-10-11 09:05:18.602264559] PoCL: in fn pocl_remote_writer_pthread at line 1145:
 |    REMOTE |  WRITER THR: WRITING MSG, TYPE: 3  ID: 1993  EVENT: 0  SIZE: msg_size: 80 + waitlist: 0 + extra: 0 + extra2: 0
[2024-10-11 09:05:18.602741260] PoCL: in fn pocl_remote_reader_pthread at line 772:
 |    REMOTE |  READER THR: MESSAGE READ, TYPE:  3  ID: 1993  SIZE: 144
[2024-10-11 09:05:18.603375138] PoCL: in fn setup_svm_memory_pool at line 446:
 |    REMOTE |  Device side SVM region missing.
Platform #0: Portable Computing Language
[2024-10-11 09:05:18.603404834] PoCL: in fn POclGetDeviceInfo at line 70:
 |   GENERAL |  clGetDeviceInfo query of param 102b for Intel(R) UHD Graphics 630
[2024-10-11 09:05:18.603428028] PoCL: in fn POclGetDeviceInfo at line 70:
 |   GENERAL |  clGetDeviceInfo query of param 102b for Intel(R) UHD Graphics 630
 `-- Device #0: Intel(R) UHD Graphics 630
liucong@liucong:~/pocl/build$ 
liucong@liucong:~/pocl/build$ 
liucong@liucong:~/pocl/build$ clinfo -l
[2024-10-11 09:05:20.982470316] PoCL: in fn find_or_create_server at line 1535:
 |    REMOTE |  using host 192.168.122.1 with port 9999
[2024-10-11 09:05:20.982756467] PoCL: in fn pocl_network_connect at line 627:
 |     ERROR | CL_INVALID_DEVICE connect() returned errno: 111
[2024-10-11 09:05:20.982772016] PoCL: in fn find_or_create_server at line 1558:
 |     ERROR |  Could not connect to server
[2024-10-11 09:05:20.982789157] PoCL: in fn pocl_network_init_device at line 1849:
 |     ERROR | CL_INVALID_DEVICE Could not connect to server 
[2024-10-11 09:05:20.982793947] PoCL: in fn pocl_init_devices at line 698:
 |     ERROR | errcode Device 0 / REMOTE initialization failed!Platform #0: Portable Computing Language
liucong@liucong:~/pocl/build$ git log --oneline -n5
fe36d461b (HEAD -> remote-socket-refactor) pocld: Wrap sockets in a Connection class
6e40d1b2c remote: Wrap sockets to make them more dynamic
4912b469e Merge pull request #1586 from pocl/coverity-badge
c3187976e (origin/coverity-badge) Add the Coverity badge
6a32dc245 Merge pull request #1581 from pjaaskel/fix-direct-pthread-usage
liucong@liucong:~/pocl/build$ git reset --hard 4912b469e
``` 

reset to 4912b469e, no issue

2024-10-12 01:10 UTC, xvim commented
Vsock is working as intended now.

2024-10-14 07:55 UTC, pjaaskel requested changes
Focused mostly on style. Let's try to converge towards our style guide.

2024-10-14 07:55 UTC, pjaaskel commented on lib/CL/devices/remote/communication.c
> +  // Gather all threads here to sleep. Last one to arrive replaces both
Pls cleanup the nearby comments to /* */ ones.

2024-10-14 07:55 UTC, pjaaskel commented on lib/CL/devices/remote/communication.h
> +typedef enum transport_domain_e
Please describe the purpose of this struct as a comment.

2024-10-14 07:55 UTC, pjaaskel commented on lib/CL/devices/remote/communication.h
> +typedef struct transport_info_s
Same here.

2024-10-14 07:55 UTC, pjaaskel commented on lib/CL/devices/remote/communication.h
> +  transport_info_t slow_connection;
Add a comment on what are these two connection types for.

2024-10-14 07:55 UTC, pjaaskel commented on pocld/reply_th.cc
> +  std::unique_lock<std::mutex> l(ConnectionGuard);
```suggestion
  std::unique_lock<std::mutex> Lock(ConnectionGuard);
```

2024-10-14 07:55 UTC, pjaaskel commented on pocld/reply_th.cc
> +    if ((io_inflight.size() > 0 || resending)) {
```suggestion
    if ((IOInflight.size() > 0 || Resending)) {
```

Take the opportunity to C++ify the style (naming) here gradually.

2024-10-14 07:55 UTC, pjaaskel commented on pocld/reply_th.cc
> +        std::unique_lock<std::mutex> l(ConnectionGuard);
```suggestion
        std::unique_lock<std::mutex> Lock(ConnectionGuard);
```

2024-10-14 07:55 UTC, pjaaskel commented on pocld/reply_th.cc
> +              Conn->writeFull(reply->extra_data.data(), reply->extra_size),
```suggestion
              Conn->writeFull(Reply->extra_data.data(), Reply->extra_size),
```

2024-10-14 07:55 UTC, pjaaskel commented on pocld/request.cc
> +      Conn->readReentrant(req, request->req_size, &request->req_read));
```suggestion
      Conn->readReentrant(Req, Request->req_size, &Request->req_read));
```

(maybe)

2024-10-14 07:55 UTC, pjaaskel commented on pocld/request.hh
> +  /** Incrementally reads the request from given Connection. Returns true on
```suggestion
  /// Incrementally reads the request from given Connection.
  ///
  /// \return true on
```

Let's try to converge to the style guide in each commit.

2024-10-14 07:55 UTC, pjaaskel commented on pocld/request_th.cc
> +  std::unique_lock<std::mutex> l(ConnectionGuard);
```suggestion
  std::unique_lock<std::mutex> Lock(ConnectionGuard);
```

2024-10-14 07:55 UTC, pjaaskel commented on pocld/request_th.cc
> +    std::unique_lock<std::mutex> l(ConnectionGuard);
```suggestion
    std::unique_lock<std::mutex> Lock(ConnectionGuard);
```

2024-10-14 07:55 UTC, pjaaskel commented on pocld/request_th.cc
> +    pfd.fd = Conn->pollableFd();
Expand the variable names a bit to improve readability.

2024-10-14 07:55 UTC, pjaaskel commented on pocld/virtual_cl_context.cc
> +  if (conns.low_latency.get())
```suggestion
  if (Conns.low_latency.get())
```

2024-10-14 07:55 UTC, pjaaskel commented on pocld/virtual_cl_context.cc
> +    write_fast->setConnection(Latency);
```suggestion
    WriteFast->setConnection(Latency);
```

2024-10-17 10:51 UTC, pjaaskel approved these changes

2024-10-17 10:51 UTC, merged