Make it possible to configure the linker path used by Clang.
pocl/pocl pull request #1621
Opened 2024-10-16 06:04 UTC by maleadt

Another env var customization to make pocl portable. Otherwise we run into compilation failures on systems that don't have a system-wide linker:

```
      From worker 3:	error: unable to execute command: Executable "ld" doesn't exist!
      From worker 3:	error: linker command failed with exit code 1 (use -v to see invocation)
      From worker 3:	Final linking of kernel sum failed.
```

We aim to use this in Julia by redistributing a copy of lld (automatically downloaded in the user's home folder) and using that binary instead.

2024-10-16 06:09 UTC, pjaaskel requested changes

2024-10-16 06:09 UTC, pjaaskel commented on lib/CL/pocl_llvm_build.cc
> +  std::string ld_path;
Let's converge towards the C++ style guide here, so please use CamelCase for variable names in C++ files.
```suggestion
  std::string LDPath;
```

2024-10-16 06:09 UTC, pjaaskel commented on lib/CL/pocl_llvm_build.cc
> +  if (const char* ld = pocl_get_path("LD", nullptr)) {
```suggestion
  if (const char* LDOverride = pocl_get_path("LD", nullptr)) {
```
(or similar).

Otherwise, LGTM!

2024-10-16 06:21 UTC, pjaaskel approved these changes

2024-10-16 06:39 UTC, pjaaskel commented
@maleadt by the way, I wonder could we use PoCL-R for distributing Julia codes?

2024-10-16 07:59 UTC, maleadt commented
> I wonder could we use PoCL-R for distributing Julia codes?

As in, offloading applications to multiple remote servers? I hadn't considered that part of PoCL yet, but I guess it would be possible. Most of the kernels we're aiming to compile with PoCL now have been written with GPUs in mind though (i.e., not scaling to very large grids, assuming reasonable latency, etc), so I'm not sure if there's enough complexity to make remote execution worthwhile. But it would be interesting!

2024-10-16 10:25 UTC, pjaaskel commented
> > I wonder could we use PoCL-R for distributing Julia codes?
> 
> As in, offloading applications to multiple remote servers? I hadn't considered that part of PoCL yet, but I guess it would be possible. Most of the kernels we're aiming to compile with PoCL now have been written with GPUs in mind though (i.e., not scaling to very large grids, assuming reasonable latency, etc), so I'm not sure if there's enough complexity to make remote execution worthwhile. But it would be interesting!

Yes, to multiple servers. PoCL-R can target any OpenCL device in the server, the server-side target doesn't have to be a PoCL-based one. If you have some interesting Julia-based test cases that could scale at the cluster level, let me know, we can try it out in some of our GPU clusters we have available.

2024-10-16 10:26 UTC, merged

2024-10-16 13:00 UTC, maleadt commented
On the topic of this PR again: looks like this isn't sufficient to fully decouple PoCL from the host environment...

```
      From worker 2:	ld.lld: error: unable to find library -lm
      From worker 2:	ld.lld: error: unable to find library -lgcc
      From worker 2:	ld.lld: error: unable to find library -lgcc_s
      From worker 2:	ld.lld: error: unable to find library -lc
      From worker 2:	ld.lld: error: unable to find library -lgcc
      From worker 2:	ld.lld: error: unable to find library -lgcc_s
```

2024-10-17 15:53 UTC, maleadt commented
Apart from the above failure, there a more direct issue: Just passing `--ld-path` doesn't suffice, as at least on Darwin the Clang driver doesn't detect its dealing with e.g. `ldd` instead of `ld`, so we need to additionally pass `-fuse-ld=ldd`.

@pjaaskel Should this become yet another env var, `POCL_LD_TYPE` or something? It's becoming somewhat messy, maybe it's better to replace this and `POCL_PATH_LD` with some way of passing arbitrary additional flags to Clang (which we would then use to set both `--ld-path` and `-fuse-ld`, and maybe additional `-L` flags to resolve the issue from https://github.com/pocl/pocl/pull/1621#issuecomment-2416777552).

2024-10-18 06:44 UTC, pjaaskel commented
Sounds like a more generic environment for passing flags at (linkage phase) to Clang is a more future-proof solution.

2024-10-18 11:32 UTC, maleadt commented
I agree, but passing an arbitrary amount of arguments over a single environment variable is error prone. Does OpenCL?PoCL have some interface to do so programmatically? Maybe custom properties with `clCreateContext`? Or just some arbitrary new extension to be looked up through `clGetExtensionFunctionAddressForPlatform`?

2024-10-18 12:32 UTC, pjaaskel commented
This would then push OpenCL-implementation-specific "driver internals" to the application layer. I'd just go with the extension for now and deal with the problems if there are any as they come.

2024-10-18 12:48 UTC, maleadt commented
So you mean a extension function that can be looked up with `clGetExtensionFunctionAddressForPlatform`? We're kinda pushing back-end specific things in the application anyway with these env vars.

2024-10-18 13:35 UTC, pjaaskel commented
Sorry, I typoed. By "extension" I meant "environment variable". Actually correct place to make this aspect more "binary portable" would be the CompilerDriver handling of Clang, right? So the longer term fix should be done in Clang while we could add the intermediate fix with yet another environment variable. Could the env even contain a command line for the full linker command and not bother trying to deal with the clang's driver interface?

2024-10-18 13:49 UTC, maleadt commented
> Actually correct place to make this aspect more "binary portable" would be the CompilerDriver handling of Clang, right?

For avoiding `-fuse-ld=lld`, sure. But passing `--ld-path` (and potential other arguments to avoid looking up system-wide stuff) would remain.

> Could the env even contain a command line for the full linker command and not bother trying to deal with the clang's driver interface?

That would put the burden on the user to figure out which platform-dependent system libraries to link (libgcc, libgcc_s, etc).

Anyway, if you prefer an env var, I'll do it that way. I'll work on a PR next week.

2024-10-18 14:40 UTC, maleadt commented
> Although not optimal, setting these via env is in my opinion better as it doesn't require modifying the client app when moving between PoCL and some other OpenCL implementation. It should work also for binary-distributed apps - right?

I guess we're looking at this from a different point of view. In Julia, we have a dedicated PoCL package (https://github.com/JuliaBinaryWrappers/pocl_jll.jl) that provides the pocl library, its dependencies, along with the possibility to execute code at load time to, say, initialize the library. It is strictly more difficult to set environment variables instead, as we need to make sure to set them early enough (i.e. before the `dlopen`), instead of being able to configure the library post-hoc.

In a more traditional setting where you, say, distribute pocl together with a launch script or a global environment configuration, I can see how environment variables are preferable.

---

All that said, I might consider a different approach first. Since we have to generate a wrapper script for `clang` anyway (to set `LD_LIBRARY_PATH`/`DYLD_LIBRARY_PATH`), maybe I should include all those arguments in there instead of passing them separately to PoCL. That avoids the implementation difficulty of having to robustly encode multiple arguments in a single string, which is highly non-trivial (especially with multiple platforms in mind -- I hope to revive Windows support some day).

2024-10-18 16:58 UTC, maleadt commented
> Since we have to generate a wrapper script for `clang` anyway (to set `LD_LIBRARY_PATH`/`DYLD_LIBRARY_PATH`), maybe I should include all those arguments in there instead of passing them separately to PoCL.

That doesn't work, it turns out; PoCL doesn't actually execute the `clang` binary, but invokes the driver part of libclang which invokes the linker directly.

2024-10-21 10:51 UTC, pjaaskel commented
> I guess we're looking at this from a different point of view. In Julia, we have a dedicated PoCL package (https://github.com/JuliaBinaryWrappers/pocl_jll.jl) that provides the pocl library, its dependencies, along with the possibility to execute code at load time to, say, initialize the library. It is strictly more difficult to set environment variables instead, as we need to make sure to set them early enough (i.e. before the `dlopen`), instead of being able to configure the library post-hoc.
> 
> In a more traditional setting where you, say, distribute pocl together with a launch script or a global environment configuration, I can see how environment variables are preferable.

I see. So you just call setenv() now before loading? Outside this Julia use case you described, I think the envs (or a PoCL configuration file, if we had one) are better for application binary-level compatibility with other OpenCL implementations.

2024-10-21 11:02 UTC, maleadt commented
> So you just call setenv() now before loading?

Pretty much.