Allow override of platform name with POCL_PLATFORM_OVERRIDE
pocl/pocl pull request #1642
Opened 2024-10-29 14:24 UTC by Leixb

OneDNN does not work if `Intel` or `OpenCL` are not part of the platform string.

https://github.com/oneapi-src/oneDNN/blob/rls-v3.6/src/xpu/sycl/utils.cpp#L96-L113

2024-10-29 14:33 UTC, pjaaskel requested changes

2024-10-29 14:33 UTC, pjaaskel commented on doc/sphinx/source/using.rst
> +- **POCL_PLATFORM_OVERRIDE**
```suggestion
- **POCL_PLATFORM_NAME_OVERRIDE**
```
Also can you move the env to the alphabetically correct place?

2024-10-29 14:33 UTC, pjaaskel commented on doc/sphinx/source/using.rst
> + Overrides the Platform reported by PoCL. For example, setting the platform
```suggestion
 Overrides the platform name reported by PoCL. For example, setting the platform
```

2024-10-29 14:33 UTC, pjaaskel commented on lib/CL/clGetPlatformInfo.c
> +      POCL_RETURN_GETINFO_STR(pocl_get_string_option("POCL_PLATFORM_OVERRIDE", "Portable Computing Language"));
Please run one of the formatter scripts under tools/scripts/ e.g. clang-format-branch.sh to fix the line length etc.

2024-10-29 16:02 UTC, pjaaskel approved these changes

2024-10-30 10:28 UTC, merged

2024-10-30 10:28 UTC, pjaaskel commented
Strictly put, oneDNN should be patched to allow PoCL platforms. Perhaps suggest also a fix there?

2024-10-30 11:09 UTC, Leixb commented
> Strictly put, oneDNN should be patched to allow PoCL platforms. Perhaps suggest also a fix there?

They already fixed the `OpenCL` detection in master. However, `Intel` in the platform name is still needed for the `is_intel_platform` check. I'll open up an issue later