remote: make the remote faster by going slower
pocl/pocl pull request #1675
Opened 2024-11-14 14:39 UTC by RABijl

for large files, use the slow queue as the fast
queue can't handle large amounts of data (like onnx blobs).

2024-11-14 15:02 UTC, jansol commented
More detailed explanation: the "low-latency" connection asks the network stack to reduce its send and receive buffers to only 4 kilobytes in order to avoid stalls due to buffering. Most PoCL-Remote commands are in the order of 100 bytes and the largest fixed-size command (DeviceInfoReply) is IIRC just a bit shy of 4 kilobytes so this works out quite nicely most of the time. However BuildProgram now takes arbitrary amounts of extra data (easily 100 kB for large OpenCL C kernels, several megabytes or even gigabytes for ONNX blobs for the new DBK API). As a result, this singular command repeatedly fills up the buffers of the TCP stack, which (presumably) triggers an automatic stop-and-wait resend request (ARQ) from the server.

As a result we can observe poll() on the server taking several milliseconds between consecutive reads for a single command, even though nothing of that sort happens when uploading content to huge buffers - PoCL-R easily sustains at least 50Gbps during buffer uploads.

Swapping BuildProgram over to use the "slow" bulk transfer socket avoids this problem and transfers are fast again with large source or binary blobs. Given the nature of this command (and it being synchronous) this seems like a much better tradeoff than the latency optimizations of the fast socket.

2024-11-14 15:03 UTC, jansol approved these changes

2024-11-14 15:06 UTC, pjaaskel requested changes
Good spot. But can you add (some of) that explanation as a comment next to the modified lines?

2024-11-15 14:32 UTC, pjaaskel approved these changes
(The nit can be fixed in the next PR.)

2024-11-15 14:32 UTC, pjaaskel commented on lib/CL/devices/remote/communication.c
> +   * of magnitudes bigger than other commands, so send this commands on the slow
```suggestion
   * of magnitudes bigger than other commands, so send this command on the slow
```

2024-11-18 12:28 UTC, RABijl commented on lib/CL/devices/remote/communication.c
> +   * of magnitudes bigger than other commands, so send this commands on the slow
fixed

2024-11-18 14:28 UTC, merged