Small fixes fox proxy and remote
pocl/pocl pull request #1739
Opened 2024-12-19 15:15 UTC by RABijl

2024-12-19 15:24 UTC, pjaaskel requested changes

2024-12-19 15:24 UTC, pjaaskel commented on lib/CL/devices/proxy/pocl_proxy.cpp
> +  if (!(d->backend->provides_metadata ||
check format

2024-12-19 18:37 UTC, RABijl commented on lib/CL/devices/proxy/pocl_proxy.cpp
> +        (d->backend->supports_il && program->program_il_size > 0)))
that is what the formatter determined was appropriate. I've moved it back a bit

2024-12-19 19:13 UTC, jansol commented on lib/CL/devices/proxy/pocl_proxy.cpp
> +        (d->backend->supports_il && program->program_il_size > 0)))
The formatter makes sense, it's aligns with the column after the innermost parenthesis around the `||` where the line was split.

2024-12-20 06:49 UTC, pjaaskel commented on lib/CL/devices/proxy/pocl_proxy.cpp
> +        (d->backend->supports_il && program->program_il_size > 0)))
OK, I'd have expected to align the if parenthesis.

2024-12-20 06:49 UTC, pjaaskel approved these changes

2024-12-20 06:49 UTC, merged