cbs: Fix hanging kernels with `unreachable`.
pocl/pocl pull request #1742
Opened 2024-12-20 10:37 UTC by fodinabor

Until now, just the first exiting basic block was reused as kernel exit. However, kernels may contain `unreachable` as exits as well. We don't want that to be our final kernel exit, though, so create a new `ret void` BB as exit.

Fixes #1711 

Thanks for reporting and the reproducer @maleadt

2024-12-20 15:03 UTC, pjaaskel requested changes

2024-12-20 15:03 UTC, pjaaskel commented on tests/regression/test_issue_1711.c
> +    cl_program program = clCreateProgramWithIL(context, binary, size, &err);
What happens with this test if SPIR-V support is not enabled in the build? Seems all CIs pass so perhaps all of them have it enabled or? Can we make the test conditional on SPIR-V support in the cmake file?

2024-12-20 15:03 UTC, pjaaskel commented on tests/regression/test_issue_1711.c
> +#include <stdio.h>
Please add (c) and license text.

2024-12-27 11:44 UTC, franz approved these changes
LGTM

2025-01-02 14:06 UTC, pjaaskel approved these changes
Thanks!

2025-01-02 14:06 UTC, merged