internal refactoring
pocl/pocl pull request #957
Opened 2021-06-17 21:15 UTC by franz

* refactors compilation callbacks
* refactor implicit buffer migrations
* allocate buffers on first enqueue instead of at clCreateBuffer()
* portability fixes (Android, MSVC)
* LTTNG tracing improved
* some random fixes

2021-06-18 14:47 UTC, pjaaskel requested changes

2021-06-18 14:47 UTC, pjaaskel commented on lib/CL/pocl_util.c
> +pocl_create_command_inner (_cl_command_node **cmd,
This function should have a comment describing what it does exactly.

2021-06-18 14:47 UTC, pjaaskel commented on lib/CL/pocl_util.c
> +pocl_create_migration_commands (cl_device_id dev, cl_event final_event,
...same here.

2021-06-18 14:47 UTC, pjaaskel commented on lib/CL/pocl_cl.h
> +#define POCL_MAGIC_1 0xBE8906A1A83D8D23ULL
What are these? Should be well-documented.

2021-06-24 09:38 UTC, franz commented on CHANGES
> +- CMake: OCS_AVAILABLE renamed to ENABLE_LLVM
At least the 2nd one is user-facing, though i suspect 99% of builds are with LLVM and only use WITH_LLVM_CONFIG cmake variable.

2021-06-24 09:38 UTC, franz commented on CHANGES
> +- IPO is enabled on code of runtime library
OK

2021-06-24 09:38 UTC, franz commented on CHANGES
> +- LTTng tracing improved
It's explained in the commit message. more tracepoints, new tracepoints for synchronous calls. I'll add  it here

2021-06-24 09:41 UTC, franz commented on CMakeLists.txt
> -  set(BUILD_BASIC 1)
I moved several "shared" driver callbacks to `lib/CL/devices/common_driver.{c,h}`

2021-06-24 09:42 UTC, franz commented on lib/CL/clCreateContext.c
> -pocl_lock_t pocl_context_handling_lock = POCL_LOCK_INITIALIZER;
yes, it's initialized by code in `devices.c`

2021-06-24 09:42 UTC, franz commented on lib/CL/pocl_cl.h
> +extern uint64_t last_object_id;
possibly, but that sounds like a thing for another PR

2021-06-24 09:42 UTC, franz commented on lib/CL/pocl_cl.h
> +  uint64_t id;
good point, will fix.

2021-07-12 11:09 UTC, pjaaskel commented on CHANGES
> +- LTTng tracing improved
I see you added more explanations to the CHANGES, which is what I of course asked for.

2021-07-12 11:16 UTC, pjaaskel commented on lib/CL/pocl_util.c
> +pocl_create_command_inner (_cl_command_node **cmd,
I suppose it was removed completely?

2021-07-12 11:22 UTC, pjaaskel approved these changes

2021-07-12 11:22 UTC, pjaaskel commented on lib/CL/pocl_cl.h
> +#define POCL_MAGIC_1 0xBE8906A1A83D8D23ULL
This is still undocumented. Reading the code it's supposed to add extra 'validness' protection by checking if the magic numbers are there or not. Do you find this useful in some case/debugging? It is not nearly fool proof anyhow, like we've discussed in the past. If we allocate a new CL object to that space in another thread, the old reference looks valid even though it was freed in between etc. If you have found it useful, please add comments to the magic numbers or even rename to them to 'sentinel' or similar slightly more descriptive which is a common name for this type trickery.

2021-07-12 12:02 UTC, pjaaskel commented
Breaks HSA. https://termbin.com/zsp7p

2021-07-13 18:14 UTC, merged