[cmake] use ninja's compile and link pools
pocl/pocl pull request #969
Opened 2021-07-25 15:53 UTC by trixirt

When CMAKE_BUILD_TYPE=DEBUG, the linking memory usage is so
high the build fails without setting -j <low_num> on the command
line.

The llvm project has a similar problem which is solved on the
ninja buildsystem by splitting the compile and link jobs.
see llvm-project/llvm/cmake/modules/HandleLLVMOptions.cmake
and these variables
LLVM_PARALLEL_COMPILE_JOBS and LLVM_PARALLEL_LINK_JOBS

The new POCL equivelent variables are
PARALLEL_COMPILE_JOBS and PARALLEL_LINK_JOBS

ex/ used in the cmake configure step
  cmake -G Ninja
   -DPARALLEL_COMPILE_JOBS=16
   -DPARALLEL_LINK_JOBS=8

And reported if used as status
...
-- OCS_AVAILABLE: ON
-- PARALLEL_COMPILE_JOBS: 16
-- PARALLEL_LINK_JOBS: 8
-- POCL_ICD_ABSOLUTE_PATH: ON
...

Signed-off-by: Tom Rix <trix@redhat.com>

2021-08-02 09:30 UTC, pjaaskel requested changes
Can you update CREDITS and perhaps CHANGES, and rebase?

2021-08-02 19:25 UTC, trixirt commented
CREDITS and CHANGES updated.  rebased to today's master.

2021-08-03 15:19 UTC, pjaaskel approved these changes

2021-08-04 13:45 UTC, trixirt commented
resolved the conflict on CREDITS

2021-08-05 07:12 UTC, merged